# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x0b\x66ilePackage\",\n\x18\x41vatarFilePreviewRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"A\n\x19\x41vatarFilePreviewResponse\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x12\n\npreviewUrl\x18\x02 \x01(\t\"8\n\x16\x41vatarPresignedRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\">\n\x17\x41vatarPresignedResponse\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x11\n\tuploadUrl\x18\x02 \x01(\t2\xd5\x01\n\x0b\x46ileService\x12\x65\n\x14GetAvatarFilePreview\x12%.filePackage.AvatarFilePreviewRequest\x1a&.filePackage.AvatarFilePreviewResponse\x12_\n\x12\x41vatarPresignedUrl\x12#.filePackage.AvatarPresignedRequest\x1a$.filePackage.AvatarPresignedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVATARFILEPREVIEWREQUEST']._serialized_start=27
  _globals['_AVATARFILEPREVIEWREQUEST']._serialized_end=71
  _globals['_AVATARFILEPREVIEWRESPONSE']._serialized_start=73
  _globals['_AVATARFILEPREVIEWRESPONSE']._serialized_end=138
  _globals['_AVATARPRESIGNEDREQUEST']._serialized_start=140
  _globals['_AVATARPRESIGNEDREQUEST']._serialized_end=196
  _globals['_AVATARPRESIGNEDRESPONSE']._serialized_start=198
  _globals['_AVATARPRESIGNEDRESPONSE']._serialized_end=260
  _globals['_FILESERVICE']._serialized_start=263
  _globals['_FILESERVICE']._serialized_end=476
# @@protoc_insertion_point(module_scope)
