# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_pb2 as file__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in file_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvatarFilePreview = channel.unary_unary(
                '/filePackage.FileService/GetAvatarFilePreview',
                request_serializer=file__pb2.AvatarFilePreviewRequest.SerializeToString,
                response_deserializer=file__pb2.AvatarFilePreviewResponse.FromString,
                _registered_method=True)
        self.AvatarPresignedUrl = channel.unary_unary(
                '/filePackage.FileService/AvatarPresignedUrl',
                request_serializer=file__pb2.AvatarPresignedRequest.SerializeToString,
                response_deserializer=file__pb2.AvatarPresignedResponse.FromString,
                _registered_method=True)


class FileServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetAvatarFilePreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvatarPresignedUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvatarFilePreview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvatarFilePreview,
                    request_deserializer=file__pb2.AvatarFilePreviewRequest.FromString,
                    response_serializer=file__pb2.AvatarFilePreviewResponse.SerializeToString,
            ),
            'AvatarPresignedUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.AvatarPresignedUrl,
                    request_deserializer=file__pb2.AvatarPresignedRequest.FromString,
                    response_serializer=file__pb2.AvatarPresignedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filePackage.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('filePackage.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvatarFilePreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filePackage.FileService/GetAvatarFilePreview',
            file__pb2.AvatarFilePreviewRequest.SerializeToString,
            file__pb2.AvatarFilePreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AvatarPresignedUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filePackage.FileService/AvatarPresignedUrl',
            file__pb2.AvatarPresignedRequest.SerializeToString,
            file__pb2.AvatarPresignedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
