name: Auth CI

on:
  push:
    branches: [main, develop]
    paths:
      - ".github/workflows/auth-ci.yaml"
      - ".github/workflows/service-ci.yaml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/auth-ci.yaml"
      - ".github/workflows/service-ci.yaml"
  workflow_run:
    workflows: ["Terraform CI"]
    types: [completed]
    branches: [main, develop]

permissions:
  contents: read
  security-events: write

env:
  COMMIT_SHA: ${{ github.event.workflow_run.head_sha || github.sha }}

jobs:
  ci:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/service-ci.yaml
    with:
      service: Auth-Service

  build-and-push:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0

      - name: Build and push auth-service-monitoring
        uses: docker/build-push-action@v7
        with:
          context: ./Auth-Service
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service-monitoring:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service-monitoring:${{ env.COMMIT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max