name: Terraform CI

on:
  push:
    branches: [main, develop]
    paths: ["Terraform/**", ".github/workflows/terraform-ci.yaml"]
  pull_request:
    branches: [main]
    paths: ["Terraform/**", ".github/workflows/terraform-ci.yaml"]

env:
  TF_VERSION: 1.15.6
  TFC_ORG: ecom
  AWS_REGION: ap-south-1
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  # ---------------------------------------------------------------------
  # 4. IaC SECURITY SCAN (Terraform / Kubernetes manifests)
  # ---------------------------------------------------------------------
  terraform-validate:
    name: Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}
        
      - run: mkdir -p "$TF_PLUGIN_CACHE_DIR"

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: github-actions-terraform-validation
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/cache@v6.0.0
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Validate
        id: validate
        run: terraform validate

  security-scanning:
    name: Security Scanning
    needs: terraform-validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: ./Terraform
          format: sarif
          output: trivy-results.sarif
          hide-progress: true
          severity: CRITICAL,HIGH

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
 
      - name: Run Checkov (Terraform + K8s)
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true
        with:
          directory: ./Terraform
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: false
 
      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: success()
        with:
          sarif_file: checkov-results.sarif

  terraform-plan:
    name: Terraform Plan
    needs: security-scanning
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: mkdir -p "$TF_PLUGIN_CACHE_DIR"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: github-actions-terraform-plan
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/cache@v6.0.0
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars -out=tfplan
        continue-on-error: true

      - name: Save Plan Text
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Upload Plan
        uses: actions/upload-artifact@v7
        with:
          name: terraform-plan
          path: Terraform/tfplan.txt
          retention-days: 5