name: Terraform CI

on:
  push:
    branches: [main, develop]
    paths: ["Terraform/**", ".github/workflows/terraform-ci.yaml"]
  pull_request:
    branches: [main]
    paths: ["Terraform/**", ".github/workflows/terraform-ci.yaml"]

env:
  TF_VERSION: 1.15.6
  TFC_ORG: ecom
  AWS_REGION: ap-south-1

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  # ---------------------------------------------------------------------
  # 4. IaC SECURITY SCAN (Terraform / Kubernetes manifests)
  # ---------------------------------------------------------------------
  terraform-validate:
    name: Infrastructure as Code Security Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_OPENID_CONNECT_PROVIDER_ARN }}
          role-session-name: ${{ secrets.AWS_IAM_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

  security-scanning:
    needs: terraform-validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
 
      - name: Run Checkov (Terraform + K8s)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: false
 
      - name: Run tfsec (Terraform-specific)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          sarif_file: tfsec-results.sarif
 
      - name: Upload Checkov SARIF
        uses: ggithub/codeql-action/upload-sarif@v1
        if: success() || failure()
        with:
          sarif_file: checkov-results.sarif
 
      - name: Upload tfsec SARIF
        uses: github/codeql-action/upload-sarif@v1
        if: success() || failure()
        with:
          sarif_file: tfsec-results.sarif

  terraform-plan:
    needs: security-scanning
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform
    steps:
    
    # Terraform Cloud Authentication
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_OPENID_CONNECT_PROVIDER_ARN }}
          role-session-name: ${{ secrets.AWS_IAM_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      - name: Upload TF Plan
        uses: actions/upload-artifact@v7.0.1
        with:
          name: tfplan
          path: tfplan